#!/bin/sh
gcc -c benchmarking/main.c -o benchmarking/object_files/main
gcc -c benchmarking/global.c -o benchmarking/object_files/global
gcc -c benchmarking/input_0.c -o benchmarking/object_files/input_0
gcc -c benchmarking/input_1.c -o benchmarking/object_files/input_1
gcc -c benchmarking/input_2.c -o benchmarking/object_files/input_2
gcc -c benchmarking/input_3.c -o benchmarking/object_files/input_3
gcc -c benchmarking/input_4.c -o benchmarking/object_files/input_4
gcc -c benchmarking/input_5.c -o benchmarking/object_files/input_5
gcc -c benchmarking/input_6.c -o benchmarking/object_files/input_6
gcc -c benchmarking/input_7.c -o benchmarking/object_files/input_7
gcc -c benchmarking/input_8.c -o benchmarking/object_files/input_8
gcc -c benchmarking/input_9.c -o benchmarking/object_files/input_9
gcc -c benchmarking/input_10.c -o benchmarking/object_files/input_10
gcc -c benchmarking/input_11.c -o benchmarking/object_files/input_11
gcc -c benchmarking/input_12.c -o benchmarking/object_files/input_12
gcc -c benchmarking/input_13.c -o benchmarking/object_files/input_13
gcc -c benchmarking/input_14.c -o benchmarking/object_files/input_14
gcc -c benchmarking/input_15.c -o benchmarking/object_files/input_15
gcc -c benchmarking/input_16.c -o benchmarking/object_files/input_16
gcc -c benchmarking/input_17.c -o benchmarking/object_files/input_17
gcc -c benchmarking/input_18.c -o benchmarking/object_files/input_18
gcc -c benchmarking/input_19.c -o benchmarking/object_files/input_19
gcc -c benchmarking/input_20.c -o benchmarking/object_files/input_20
gcc -c benchmarking/input_21.c -o benchmarking/object_files/input_21
gcc -c benchmarking/input_22.c -o benchmarking/object_files/input_22
gcc -c benchmarking/input_23.c -o benchmarking/object_files/input_23
gcc -c benchmarking/input_24.c -o benchmarking/object_files/input_24
gcc -c benchmarking/input_25.c -o benchmarking/object_files/input_25
gcc -c benchmarking/input_26.c -o benchmarking/object_files/input_26
gcc -c benchmarking/input_27.c -o benchmarking/object_files/input_27
gcc -c benchmarking/input_28.c -o benchmarking/object_files/input_28
gcc -c benchmarking/input_29.c -o benchmarking/object_files/input_29
gcc -c benchmarking/input_30.c -o benchmarking/object_files/input_30
gcc -c benchmarking/input_31.c -o benchmarking/object_files/input_31
gcc -c benchmarking/input_32.c -o benchmarking/object_files/input_32
gcc -c benchmarking/input_33.c -o benchmarking/object_files/input_33
gcc -c benchmarking/input_34.c -o benchmarking/object_files/input_34
gcc -c benchmarking/input_35.c -o benchmarking/object_files/input_35
gcc -c benchmarking/input_36.c -o benchmarking/object_files/input_36
gcc -c benchmarking/input_37.c -o benchmarking/object_files/input_37
gcc -c benchmarking/input_38.c -o benchmarking/object_files/input_38
gcc -c benchmarking/input_39.c -o benchmarking/object_files/input_39
gcc -c benchmarking/input_40.c -o benchmarking/object_files/input_40
gcc -c benchmarking/input_41.c -o benchmarking/object_files/input_41
gcc -c benchmarking/input_42.c -o benchmarking/object_files/input_42
gcc -c benchmarking/input_43.c -o benchmarking/object_files/input_43
gcc -c benchmarking/input_44.c -o benchmarking/object_files/input_44
gcc -c benchmarking/input_45.c -o benchmarking/object_files/input_45
gcc -c benchmarking/input_46.c -o benchmarking/object_files/input_46
gcc -c benchmarking/input_47.c -o benchmarking/object_files/input_47
gcc -c benchmarking/input_48.c -o benchmarking/object_files/input_48
gcc -c benchmarking/input_49.c -o benchmarking/object_files/input_49
gcc -c benchmarking/input_50.c -o benchmarking/object_files/input_50
gcc -c benchmarking/input_51.c -o benchmarking/object_files/input_51
gcc -c benchmarking/input_52.c -o benchmarking/object_files/input_52
gcc -c benchmarking/input_53.c -o benchmarking/object_files/input_53
gcc -c benchmarking/input_54.c -o benchmarking/object_files/input_54
gcc -c benchmarking/input_55.c -o benchmarking/object_files/input_55
gcc -c benchmarking/input_56.c -o benchmarking/object_files/input_56
gcc -c benchmarking/input_57.c -o benchmarking/object_files/input_57
gcc -c benchmarking/input_58.c -o benchmarking/object_files/input_58
gcc -c benchmarking/input_59.c -o benchmarking/object_files/input_59
gcc -c benchmarking/input_60.c -o benchmarking/object_files/input_60
gcc -c benchmarking/input_61.c -o benchmarking/object_files/input_61
gcc -c benchmarking/input_62.c -o benchmarking/object_files/input_62
gcc -c benchmarking/input_63.c -o benchmarking/object_files/input_63
gcc -c benchmarking/input_64.c -o benchmarking/object_files/input_64
gcc -c benchmarking/input_65.c -o benchmarking/object_files/input_65
gcc -c benchmarking/input_66.c -o benchmarking/object_files/input_66
gcc -c benchmarking/input_67.c -o benchmarking/object_files/input_67
gcc -c benchmarking/input_68.c -o benchmarking/object_files/input_68
gcc -c benchmarking/input_69.c -o benchmarking/object_files/input_69
gcc -c benchmarking/input_70.c -o benchmarking/object_files/input_70
gcc -c benchmarking/input_71.c -o benchmarking/object_files/input_71
gcc -c benchmarking/input_72.c -o benchmarking/object_files/input_72
gcc -c benchmarking/input_73.c -o benchmarking/object_files/input_73
gcc -c benchmarking/input_74.c -o benchmarking/object_files/input_74
gcc -c benchmarking/input_75.c -o benchmarking/object_files/input_75
gcc -c benchmarking/input_76.c -o benchmarking/object_files/input_76
gcc -c benchmarking/input_77.c -o benchmarking/object_files/input_77
gcc -c benchmarking/input_78.c -o benchmarking/object_files/input_78
gcc -c benchmarking/input_79.c -o benchmarking/object_files/input_79
gcc -c benchmarking/input_80.c -o benchmarking/object_files/input_80
gcc -c benchmarking/input_81.c -o benchmarking/object_files/input_81
gcc -c benchmarking/input_82.c -o benchmarking/object_files/input_82
gcc -c benchmarking/input_83.c -o benchmarking/object_files/input_83
gcc -c benchmarking/input_84.c -o benchmarking/object_files/input_84
gcc -c benchmarking/input_85.c -o benchmarking/object_files/input_85
gcc -c benchmarking/input_86.c -o benchmarking/object_files/input_86
gcc -c benchmarking/input_87.c -o benchmarking/object_files/input_87
gcc -c benchmarking/input_88.c -o benchmarking/object_files/input_88
gcc -c benchmarking/input_89.c -o benchmarking/object_files/input_89
gcc -c benchmarking/input_90.c -o benchmarking/object_files/input_90
gcc -c benchmarking/input_91.c -o benchmarking/object_files/input_91
gcc -c benchmarking/input_92.c -o benchmarking/object_files/input_92
gcc -c benchmarking/input_93.c -o benchmarking/object_files/input_93
gcc -c benchmarking/input_94.c -o benchmarking/object_files/input_94
gcc -c benchmarking/input_95.c -o benchmarking/object_files/input_95
gcc -c benchmarking/input_96.c -o benchmarking/object_files/input_96
gcc -c benchmarking/input_97.c -o benchmarking/object_files/input_97
gcc -c benchmarking/input_98.c -o benchmarking/object_files/input_98
gcc -c benchmarking/input_99.c -o benchmarking/object_files/input_99
